### ISSUE TITLE
Generate random valid CC number 

### ISSUE THREAD

**Issue by msramalho** [Dannyps/CCidadao#1]
is this possible?

**Comment by Dannyps** [comment]
Surely. Just provide a random $num and a random version number (lower is better, as CC numbers are a recent thing) and this library will be able to compute both check digits ($ccd and $vcd).

**Comment by msramalho** [comment]
I see, so all the `$num` are valid, if accompanied by the correct check digits?

**Comment by Dannyps** [comment]
Yes. They may not be assigned to anyone, but they’re valid.
