### ISSUE TITLE
Cannot use dannyps/ccidadao's latest version v0.2.1 as it requires php ^7.0.0 which is not satisfied by your platform.  

### ISSUE THREAD

**Issue by antonyshin** [Dannyps/CCidadao#7]
Cannot use dannyps/ccidadao's latest version v0.2.1 as it requires php ^7.0.0 which is not satisfied by your platform.

In PackageDiscoveryTrait.php line 325:
                                                                                                                      
  Package Dannyps/CCidadao has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - dannyps/ccidadao v0.2.1 requires php ^7.0.0 which does not match your installed version 8.2.14.                 
                                                                                                                      

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by antonyshin** [comment]
![image](https://github.com/user-attachments/assets/1df8f784-13bb-4df3-848a-35bc58b76c06)

**Comment by Dannyps** [comment]
Hi, @antonyshin. I have not been actively maintaining this package, and did not enable it for PHP8, which is what you seem to be using. I may do that soon, nevertheless. I'll let you know.

**Comment by Dannyps** [comment]
Ok, that was fast. There was already some work done!
You should be good now by using the latest version https://packagist.org/packages/dannyps/ccidadao#v0.2.2
